### ISSUE TITLE
test

### ISSUE THREAD

**Issue by wrightaprilm** [macrojc/macrojc#1]
Do we all get an e-mail?

**Comment by richfitz** [comment]
I got an email!

**Comment by nhcooper123** [comment]
me too
---------------------------------------------------------
Dr Natalie Cooper
Assistant Professor
Macroecology and Macroevolution Research Group

School of Natural Sciences
Trinity College Dublin
2 College Green, Dublin 2
+353 (0)1 896 1926 (work)
+353 (0) 87193 5856 (mobile)

Twitter: @nhcooper123
EcoEvo@TCD blog: www.ecoevoblog.com
Webpage: http://www.tcd.ie/Zoology/research/ncooper/nataliecooper.php
________________________________________
