### ISSUE TITLE
OK now I'm obsessed...what do you think of this posting idea?

### ISSUE THREAD

**Issue by nhcooper123** [macrojc/macrojc#4]
I've put up a post about tonight. Feel free to edit (in fact please do as I'm really very tired and may be talking crap). I figure if one of us writes a brief summary like this at least it reminds us what we discussed and makes us look like we're doing something, but also isn't difficult or time consuming! I've also added a "funny" section at the end for the amusing non-academic stuff. We can also add memes. Rich should find his "box of monophyly" one, and the one with all the graptolites! 

Does that sound reasonable? Total open to other suggestions! :)

**Comment by dwbapst** [comment]
"why can't we publish useful (but dull) papers showing simple conditions
under which our models breakdown (i.e. when is branch length error
important, when do we need to fix it and when can we "ignore" it)"

...I sort of did publish that paper, and it was rather dull.

On Wed, Feb 4, 2015 at 4:30 PM, Natalie Cooper <notifications@github.com>
wrote:

> I've put up a post about tonight. Feel free to edit (in fact please do as
> I'm really very tired and may be talking crap). I figure if one of us
> writes a brief summary like this at least it reminds us what we discussed
> and makes us look like we're doing something, but also isn't difficult or
> time consuming! I've also added a "funny" section at the end for the
> amusing non-academic stuff. We can also add memes. Rich should find his
> "box of monophyly" one, and the one with all the graptolites!
>
> Does that sound reasonable? Total open to other suggestions! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/macrojc/macrojc/issues/4>.
>



-- 
David W. Bapst, PhD
Adjunct Asst. Professor, Geology and Geol. Eng.
South Dakota School of Mines and Technology
501 E. St. Joseph
Rapid City, SD 57701

http://webpages.sdsmt.edu/~dbapst/
http://cran.r-project.org/web/packages/paleotree/index.html

**Comment by josephwb** [comment]
Let the memes begin...

![mcmc_fail](https://cloud.githubusercontent.com/assets/808499/6053456/94886416-acad-11e4-9fa5-6ff57579c259.jpg)

**Comment by graemetlloyd** [comment]
![58856179](https://cloud.githubusercontent.com/assets/7533214/6066567/4965b40e-ad6e-11e4-8411-11b5f26ffe4d.jpg)
